"""removing unique name

Revision ID: f6ba9dc238a9
Revises: 38f17a563df9
Create Date: 2022-03-18 13:39:45.763539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ba9dc238a9'
down_revision = '38f17a563df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    # ### end Alembic commands ###
